---

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - python3-pip
    - python3-pymysql
    - python3-full

#- name: Install PyMySQL python library
#  ansible.builtin.pip:
#    name: pymysql
#    state: present

- name: Check if a custom root password is specified
  ansible.builtin.debug:
    msg: >
      Warning!! the MariaDB root password was left empty. Please set a custom
      password with role variable mariadb_root_password to secure your database
      server!
  when: not mariadb_root_password
  tags: mariadb

# This command will exit non-zero when the root password was set previously
- name: Check if root password is unset
  ansible.builtin.shell: >
    mysql -u root
    -p'{{ mariadb_root_password }}'
    -h localhost
    -S {{ mariadb_socket }}
    -e "quit"
  changed_when: false
  ignore_errors: true
  register: root_pwd_check
  tags: mariadb

# Repeat runs with the same password can continue idempotently, otherwise fail.
- name: Check if the specified root password is already set
  ansible.builtin.shell: >
    mysqladmin -u root -p{{ mariadb_root_password }} status
  changed_when: false
  no_log: true
  when: root_pwd_check.rc != 0
  tags: mariadb

- name: Check for previously set unix_socket in plugin column
  ansible.builtin.command: >
    mysql -N -s -S {{ mariadb_socket }} -u root -e
    "SELECT plugin from mysql.user WHERE user = 'root'"
  register: plugin_root_result
  changed_when: plugin_root_result.stdout is search('unix_socket')
  when: root_pwd_check.rc == 0
  tags: mariadb

- name: Set MariaDB root password for the first time (root@localhost)
  community.mysql.mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  when: root_pwd_check.rc != 0
  tags: mariadb

- name: Set bind address
  ansible.builtin.lineinfile:
    path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    regexp: "^bind-address"
    line: ""
  notify:
    - Restart mysqld



